# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_module.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11grpc_module.proto\x12\x11your_package_name\"\x0e\n\x0cHelloRequest\"3\n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x32_\n\x0cHelloService\x12O\n\x08SayHello\x12\x1f.your_package_name.HelloRequest\x1a .your_package_name.HelloResponse\"\x00\x62\x06proto3')



_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_HELLORESPONSE = DESCRIPTOR.message_types_by_name['HelloResponse']
HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'grpc_module_pb2'
  # @@protoc_insertion_point(class_scope:your_package_name.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloResponse = _reflection.GeneratedProtocolMessageType('HelloResponse', (_message.Message,), {
  'DESCRIPTOR' : _HELLORESPONSE,
  '__module__' : 'grpc_module_pb2'
  # @@protoc_insertion_point(class_scope:your_package_name.HelloResponse)
  })
_sym_db.RegisterMessage(HelloResponse)

_HELLOSERVICE = DESCRIPTOR.services_by_name['HelloService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=40
  _HELLOREQUEST._serialized_end=54
  _HELLORESPONSE._serialized_start=56
  _HELLORESPONSE._serialized_end=107
  _HELLOSERVICE._serialized_start=109
  _HELLOSERVICE._serialized_end=204
# @@protoc_insertion_point(module_scope)
